# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{magento}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gary Taylor", "Tim Matheson"]
  s.date = %q{2010-10-06}
  s.email = %q{gary.taylor@rubysystems.co.uk}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "lib/abstract.rb",
     "lib/category.rb",
     "lib/configuration.rb",
     "lib/country.rb",
     "lib/customer.rb",
     "lib/customer_address.rb",
     "lib/customer_groups.rb",
     "lib/extensions.rb",
     "lib/inventory.rb",
     "lib/invoice.rb",
     "lib/magento.rb",
     "lib/order.rb",
     "lib/product.rb",
     "lib/product_images.rb",
     "lib/product_types.rb",
     "lib/region.rb",
     "lib/server.rb",
     "lib/shipment.rb",
     "lib/tasks/setup.rake"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Magento API Wrapper For Rails 3}
  s.test_files = [
    "spec/customer_spec.rb",
     "spec/inventory_spec.rb",
     "spec/magento_spec.rb",
     "spec/order_spec.rb",
     "spec/spec_helper.rb",
     "spec/xmlrpc_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<railties>, [">= 0"])
    else
      s.add_dependency(%q<railties>, [">= 0"])
    end
  else
    s.add_dependency(%q<railties>, [">= 0"])
  end
end

